# **tf-idf sample**

* dokumen 1: 'apel merah enak'
* dokumen 2: 'apel hijau segar'
* dokumen 3: 'apel merah segar'

* TF: jumlah kemunculan kata dalam dokumen
> dokumen 1: 'apel' = 1, 'merah' = 1
> dokumen 2: 'apel' = 1, 'hijau' = 1

* DF: jumlah dokumen yang mengandung suatu kata $t$
> DF('apel') = 2 dokumen

* IDF

$$
IDF(t) = \log \left(\frac{N}{DF}\right) = \log \left(\frac{\text{jumlah dokumen}}{DF}\right)
$$

## Key concept

In [35]:
import pandas as pd
import numpy as np
import sys
sys.path.append('..')
from src.preprocessing import preprotext
from src.utils import build_vocab

In [36]:
documents = [
    'apel merah enak',
    'apel hijau segar',
    'apel merah segar'
]

df = pd.DataFrame(documents)
df.columns = ['documents']

In [37]:
df

          documents
0   apel merah enak
1  apel hijau segar
2  apel merah segar

In [38]:
vocab = build_vocab(df['documents'])

In [39]:
documents = df['documents']
cleaned_documents = documents.copy()

for i in range(documents.shape[0]):
    cleaned_documents.iloc[i] = preprotext(cleaned_documents.iloc[i])

In [40]:
cleaned_documents

0     [apel, merah, enak]
1    [apel, hijau, segar]
2    [apel, merah, segar]
Name: documents, dtype: object

## Term Frequency

In [41]:
def termFrequency(document, vocab):
    tf = dict()
    count = 0
    for token in document:
        if token in vocab:
            count += 1
            freq = {token: count}
            tf.update(freq)
            count = 0
    return tf

In [42]:
tf_list = []
for docs in cleaned_documents:
    docs = termFrequency(docs, vocab)
    tf_list.append(docs)

In [43]:
tf_list

[{'apel': 1, 'merah': 1, 'enak': 1},
 {'apel': 1, 'hijau': 1, 'segar': 1},
 {'apel': 1, 'merah': 1, 'segar': 1}]

## Document Frequency

Jumlah dokumen yang mengandung kata $t$

misalnya DF('apel') = 3

In [24]:
tf0 = tf_list[0]

for keys in tf0:
    print(f'key: {keys}')
    print(f'value: {tf0.get(keys)}')

key: apel
value: 1
key: merah
value: 1
key: enak
value: 1

In [ ]:
df_list = []
count = 0
for tf in tf_list:
    for keys in tf:
        df_list.append(keys)

In [32]:
doc_freq = dict()
count = 0
for term in df_list:
    freq = {term: df_list.count(term)}
    doc_freq.update(freq)

In [49]:
doc_freq

{'apel': 3, 'merah': 2, 'enak': 1, 'hijau': 1, 'segar': 2}

In [ ]:
for term in df_list:
    count = df_list.count(term)
    print(f'term: {term}, count: {count}')

term: apel, count: 3
term: merah, count: 2
term: enak, count: 1
term: apel, count: 3
term: hijau, count: 1
term: segar, count: 2
term: apel, count: 3
term: merah, count: 2
term: segar, count: 2

In [ ]:
def docFrequency(TF):
    docList = []
    docFreq = dict()
    for termfreqs in TF:
        for keys in termfreqs:
            docList.append(keys)
    
    for term in docList:
        freq = {term: docList.count(term)}
        docFreq.update(freq)
        
    return docFreq

In [50]:
tf_list

[{'apel': 1, 'merah': 1, 'enak': 1},
 {'apel': 1, 'hijau': 1, 'segar': 1},
 {'apel': 1, 'merah': 1, 'segar': 1}]

In [51]:
for tf in tf_list:
    for keys in tf:
        print(keys)

apel
merah
enak
apel
hijau
segar
apel
merah
segar

In [53]:
doc_list = docFrequency(tf_list)

apel
merah
enak
apel
hijau
segar
apel
merah
segar

In [54]:
print(doc_list)

{'apel': 3, 'merah': 2, 'enak': 1, 'hijau': 1, 'segar': 2}

## experiment on dataset/emails.csv

In [ ]:
# tf idf
import pandas as pd
import numpy as np
import sys
sys.path.append('..')

In [ ]:
df = pd.read_csv('../data/emails.csv')
sample = df.iloc[:3]
sample

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1

In [ ]:
sample['text'], sample['spam']

(0    Subject: naturally irresistible your corporate...
 1    Subject: the stock trading gunslinger  fanny i...
 2    Subject: unbelievable new homes made easy  im ...
 Name: text, dtype: object,
 0    1
 1    1
 2    1
 Name: spam, dtype: int64)

In [ ]:
from src.preprocessing import preprotext

documents = sample['text']
for i in range(len(sample)):
    documents.iloc[i] = preprotext(documents.iloc[i])

C:\Users\nadhi\AppData\Local\Temp\ipykernel_10692\765759015.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  documents.iloc[i] = preprotext(documents.iloc[i])
C:\Users\nadhi\AppData\Local\Temp\ipykernel_10692\765759015.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  documents.iloc[i] = preprotext(documents.iloc[i])
C:\Users\nadhi\AppData\Local\Temp\ipykernel_10692\765759015.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  documents.iloc[i] = preprotext(documents.iloc[i])

In [ ]:
from src.utils import build_vocab

vocab = build_vocab(sample)

ImportError: cannot import name 'build_vocab' from 'src.utils' (d:\Code-related\Code Projects\Python Projects\Spam\notebooks\..\src\utils.py)

In [ ]:
def build_vocab(documents):
    """Building list of words from train data for model. The function could be used as:
    vocab = build_vocab(cleaned_texts)
    len(vocab), vocab

    Args:
        documents: LIST of 

    Returns:
        list: vocabulary
    """
    vocab = []
    for document in documents:
        tokens = preprotext(document) # resulting tokens of each documents
        for token in tokens:
            vocab.append(token)
    
    vocab = list(set(vocab))
    vocab = {word: index for index, word in enumerate(vocab)}
    return vocab

In [ ]:
vocab = build_vocab(sample['text'])

In [ ]:
vocab

{'group': 0,
 'really': 1,
 'trading': 2,
 'factor': 3,
 'muzo': 4,
 'iogo': 5,
 'see': 6,
 'practicable': 7,
 'love': 8,
 'optima': 9,
 'complete': 10,
 '1': 11,
 'all': 12,
 'clockwork': 13,
 'benefits': 14,
 'original': 15,
 'satisfaction': 16,
 'portfolio': 17,
 'days': 18,
 'attainder': 19,
 'changes': 20,
 'without': 21,
 'opportunity': 22,
 'creativeness': 23,
 'unbelievable': 24,
 'through': 25,
 'much': 26,
 'form': 27,
 'segovia': 28,
 'huzzah': 29,
 'gunslinger': 30,
 'have': 31,
 'limited': 32,
 'hearing': 33,
 'nowadays': 34,
 'extra': 35,
 'that': 36,
 'content': 37,
 'even': 38,
 'efforts': 39,
 'advantage': 40,
 'plain': 41,
 'pepperoni': 42,
 'and': 43,
 'make': 44,
 'a': 45,
 'corporate': 46,
 'wanting': 47,
 'logos': 48,
 'like': 49,
 'this': 50,
 'attire': 51,
 'look': 52,
 'pirogue': 53,
 'continuant': 54,
 'formats': 55,
 'three': 56,
 'boar': 57,
 'rate': 58,
 'the': 59,
 'nameable': 60,
 'extended': 61,
 'home': 62,
 'become': 63,
 'image': 64,
 'letsyou': 65,
 'albeit': 66,
 'herald': 67,
 '169': 68,
 'stock': 69,
 'inflexible': 70,
 'ieader': 71,
 'slung': 72,
 'statlonery': 73,
 'ordered': 74,
 'havinq': 75,
 'new': 76,
 'fees': 77,
 'logo': 78,
 '3': 79,
 'good': 80,
 'aim': 81,
 'incredible': 82,
 'take': 83,
 'provide': 84,
 'convenience': 85,
 'way': 86,
 'promise': 87,
 'im': 88,
 'ramble': 89,
 'minute': 90,
 'gaps': 91,
 'website': 92,
 'been': 93,
 'loan': 94,
 'chameleon': 95,
 'show': 96,
 'suqgestions': 97,
 'hawthorn': 98,
 'ask': 99,
 'post': 100,
 'homeowner': 101,
 'our': 102,
 '72': 103,
 'made': 104,
 't': 105,
 'fixed': 106,
 'it': 107,
 'system': 108,
 '454': 109,
 'to': 110,
 'company': 111,
 'not': 112,
 'easier': 113,
 'stationery': 114,
 'break': 115,
 'for': 116,
 'kansas': 117,
 'affordability': 118,
 'approval': 119,
 'at': 120,
 'lt': 121,
 'dorcas': 122,
 'automaticaily': 123,
 'of': 124,
 'fanny': 125,
 'more': 126,
 'palfrey': 127,
 'easy': 128,
 'use': 129,
 'sapling': 130,
 'merrill': 131,
 'isguite': 132,
 'you': 133,
 'specially': 134,
 'hepburn': 135,
 'identity': 136,
 'chesapeake': 137,
 'waterway': 138,
 'world': 139,
 'done': 140,
 'its': 141,
 'chisel': 142,
 'pre': 143,
 'task': 144,
 'chronography': 145,
 'hotat': 146,
 'duane': 147,
 'from': 148,
 'clear': 149,
 'provided': 150,
 'reflect': 151,
 '100': 152,
 'isoverwhelminq': 153,
 'stylish': 154,
 'einsteinian': 155,
 'diffusion': 156,
 'result': 157,
 'foward': 158,
 'promptness': 159,
 'deoxyribonucleic': 160,
 'subject': 161,
 'list': 162,
 'hall': 163,
 'your': 164,
 'information': 165,
 'catchy': 166,
 'outstanding': 167,
 'budget': 168,
 'market': 169,
 'pittman': 170,
 'guaranteed': 171,
 'interested': 172,
 'distinctive': 173,
 'unlimited': 174,
 'recollect': 175,
 'try': 176,
 'mcdougall': 177,
 'naturally': 178,
 'edt': 179,
 'earmark': 180,
 'credit': 181,
 'management': 182,
 'irresistible': 183,
 'but': 184,
 'we': 185,
 'surethat': 186,
 'with': 187,
 'marketing': 188,
 'be': 189,
 'colza': 190,
 'ciear': 191,
 'esmark': 192,
 'libretto': 193,
 'visit': 194,
 'unconditionally': 195,
 'shouldn': 196,
 'hard': 197,
 'amount': 198,
 'within': 199,
 'tight': 200,
 'drafts': 201,
 'perspicuous': 202,
 'offer': 203,
 'here': 204,
 'or': 205,
 'time': 206,
 'effective': 207,
 'business': 208,
 'change': 209,
 'is': 210,
 'do': 211,
 'being': 212,
 'products': 213,
 'yes': 214,
 'are': 215,
 'superior': 216,
 'full': 217,
 'hand': 218,
 'bedtime': 219,
 'no': 220,
 'homes': 221,
 'organization': 222,
 'collaboration': 223,
 'penultimate': 224,
 'structure': 225,
 'morristown': 226,
 'tanzania': 227,
 'approved': 228,
 'clothesman': 229,
 'in': 230,
 'will': 231}

In [ ]:
def termFreq(documents):
    """Menghitung jumlah kemunculan kata dalam setiap dokumen

    Args:
        documents (_type_): _description_

    Returns:
        _type_: _description_
    """
    
    list_tf = []
    
    return list_tf